#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if command -v remove-shell >/dev/null 2>&1; then
            remove-shell /usr/bin/oosh
        elif [ -f /etc/shells ]; then
            sed -i -e '\|^/usr/bin/oosh$|d' /etc/shells 2>/dev/null || true
        fi
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        ;;
esac

exit 0
